# Generated by Django 3.0.3 on 2020-06-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('img_id', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField(default=0)),
                ('total_recovers', models.IntegerField(default=0)),
                ('total_hospitals', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('my_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Articles genre (e.g. Finance)', max_length=200)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='MyModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
            options={
                'ordering': ['-my_field_name'],
            },
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('dir', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Tweets',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(help_text='Enter your First Name ', max_length=200)),
                ('Last_name', models.CharField(help_text='Enter your Last Name ', max_length=200)),
                ('email', models.CharField(help_text='Enter your email ', max_length=200)),
                ('area', models.CharField(help_text='Enter your area ', max_length=200)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('area_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area')),
            ],
            options={
                'db_table': 'SuperMarket',
            },
        ),
        migrations.CreateModel(
            name='Recovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area')),
            ],
            options={
                'db_table': 'Recovered',
            },
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('area_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area')),
            ],
            options={
                'db_table': 'Pharmacies',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('area_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area')),
            ],
            options={
                'db_table': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='Diagramms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('area_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area')),
            ],
            options={
                'db_table': 'Diagramms',
            },
        ),
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area')),
            ],
            options={
                'db_table': 'Deaths',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dead', models.BooleanField(default=False)),
                ('recovered', models.BooleanField(default=False)),
                ('on_going', models.BooleanField(default=True)),
                ('area_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area')),
            ],
            options={
                'db_table': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='covid_19_update.Author')),
                ('genre', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Genre')),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
    ]
