# Generated by Django 3.0.3 on 2020-05-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='genre',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Genre'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='area_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area'),
        ),
        migrations.AlterField(
            model_name='diagramms',
            name='area_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='area_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area'),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='area_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='area_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='covid_19_update.Area'),
        ),
    ]
