# Generated by Django 3.0.3 on 2020-06-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19_update', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='date_published',
        ),
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
