# Generated by Django 3.0.3 on 2020-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19_update', '0002_auto_20200609_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
