# Generated by Django 3.0.3 on 2020-06-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19_update', '0003_auto_20200609_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='auth',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
