# Generated by Django 3.0.3 on 2020-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19_update', '0005_tweets_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacies',
            name='map',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
